# Generated by Django 5.2 on 2025-04-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('Lab', 'Lab'), ('Theatre', 'Theatre')], max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
