# Generated by Django 5.2 on 2025-04-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_course_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'semester')},
        ),
    ]
