# Generated by Django 5.2 on 2025-04-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_course_credits_course_number_of_labs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
