# Generated by Django 5.2 on 2025-04-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_teacher_email_teacher_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=255)),
                ('day', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=255)),
            ],
        ),
    ]
