# Generated by Django 5.2 on 2025-04-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_timetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.teacher'),
        ),
    ]
